import { describe, expect, it } from "bun:test";
import { createAgentOrchestratorPlugin } from "./index";

describe("createAgentOrchestratorPlugin", () => {
  it("exposes orchestration summary metadata from the native service", async () => {
    const plugin = createAgentOrchestratorPlugin({
      delegation: {
        create: () => ({
          id: "task-1",
          title: "Task 1",
          objective: "Do task 1",
          status: "pending",
          executionMode: "local",
          notes: [],
          createdAt: "2026-03-24T00:00:00.000Z",
          updatedAt: "2026-03-24T00:00:00.000Z",
        }),
        list: () => [
          {
            id: "task-1",
            title: "Task 1",
            objective: "Do task 1",
            status: "pending",
            executionMode: "local",
            notes: [],
            createdAt: "2026-03-24T00:00:00.000Z",
            updatedAt: "2026-03-24T00:00:00.000Z",
          },
          {
            id: "task-2",
            title: "Task 2",
            objective: "Do task 2",
            status: "running",
            executionMode: "delegated",
            notes: [],
            createdAt: "2026-03-24T00:00:00.000Z",
            updatedAt: "2026-03-24T00:00:00.000Z",
          },
        ],
        get: (id) => ({
          id,
          title: `Task ${id}`,
          objective: `Do ${id}`,
          status: "pending",
          executionMode: "local",
          notes: [],
          createdAt: "2026-03-24T00:00:00.000Z",
          updatedAt: "2026-03-24T00:00:00.000Z",
        }),
        queueSummary: () => ({
          total: 2,
          pending: 1,
          running: 1,
          completed: 0,
          failed: 0,
          cancelled: 0,
          retryable: 0,
          delegated: 1,
          local: 1,
          inlineWorkers: 0,
          processWorkers: 1,
          activeWorkers: 2,
          aliveWorkers: 1,
          stalledWorkers: 0,
          concurrency: 1,
          byProfile: [],
          byPriority: [],
          byGroup: [],
          byLabel: [],
        }),
        overview: () => ({
          total: 2,
          pending: 1,
          running: 1,
          completed: 0,
          failed: 0,
          cancelled: 0,
          retryable: 0,
          delegated: 1,
          local: 1,
          inlineWorkers: 0,
          processWorkers: 1,
          activeWorkers: 2,
          aliveWorkers: 1,
          stalledWorkers: 0,
          concurrency: 1,
          byProfile: [],
          byPriority: [],
          byGroup: [],
          byLabel: [],
        }),
        getChildren: () => [
          {
            id: "child-1",
            title: "Child 1",
            objective: "Do child 1",
            status: "pending",
            executionMode: "local",
            notes: [],
            createdAt: "2026-03-24T00:00:00.000Z",
            updatedAt: "2026-03-24T00:00:00.000Z",
          },
        ],
        tree: (id) => ({
          task: {
            id,
            title: `Task ${id}`,
            objective: `Do ${id}`,
            status: "pending",
            executionMode: "local",
            notes: [],
            createdAt: "2026-03-24T00:00:00.000Z",
            updatedAt: "2026-03-24T00:00:00.000Z",
          },
          children: [],
        }),
        spawnChild: () => ({
          id: "child-1",
          title: "Child 1",
          objective: "Do child 1",
          status: "pending",
          executionMode: "local",
          notes: [],
          createdAt: "2026-03-24T00:00:00.000Z",
          updatedAt: "2026-03-24T00:00:00.000Z",
        }),
        retryTask: () => ({
          id: "task-1",
          title: "Task 1",
          objective: "Do task 1",
          status: "pending",
          executionMode: "local",
          notes: [],
          createdAt: "2026-03-24T00:00:00.000Z",
          updatedAt: "2026-03-24T00:00:00.000Z",
        }),
        cancel: () => ({
          id: "task-1",
          title: "Task 1",
          objective: "Do task 1",
          status: "cancelled",
          executionMode: "local",
          notes: [],
          createdAt: "2026-03-24T00:00:00.000Z",
          updatedAt: "2026-03-24T00:00:00.000Z",
        }),
        supervise: async () => ({
          concurrency: 1,
          started: ["task-1"],
          completed: ["task-1"],
          failed: [],
          skipped: [],
          overview: {
            total: 2,
            pending: 1,
            running: 0,
            completed: 1,
            failed: 0,
            cancelled: 0,
            retryable: 0,
            delegated: 0,
            local: 2,
            inlineWorkers: 0,
            processWorkers: 0,
            activeWorkers: 2,
            aliveWorkers: 0,
            stalledWorkers: 0,
            concurrency: 1,
            byProfile: [],
            byPriority: [],
            byGroup: [],
            byLabel: [],
          },
        }),
        runQueued: async () => [
          {
            id: "task-1",
            title: "Task 1",
            objective: "Do task 1",
            status: "completed",
            executionMode: "local",
            notes: [],
            createdAt: "2026-03-24T00:00:00.000Z",
            updatedAt: "2026-03-24T00:00:00.000Z",
          },
        ],
      },
    });

    const ServiceCtor = plugin.services?.[0] as unknown as {
      start(runtime?: unknown): Promise<{
        summary(): unknown;
      }>;
    };
    const service = await ServiceCtor.start();
    expect(service.summary()).toEqual({
      tasks: 2,
      queuePending: 1,
      activeWorkers: 2,
      childTasksSupported: true,
      treeSupported: true,
      retrySupported: true,
    });
  });
});
