import { describe, expect, it } from "bun:test";
import type { DelegationAggregationSummary } from "./contracts";
import { createAgentOrchestratorPlugin } from "./index";

const orchestrationBreakdown = [{ mode: "sequential", count: 2 }] as const;
const completedAggregation: DelegationAggregationSummary[] = [
  {
    rootTaskId: "task-1",
    orchestrationMode: "sequential",
    totalTasks: 1,
    completedTasks: 1,
    failedTasks: 0,
    cancelledTasks: 0,
    runningTasks: 0,
    pendingTasks: 0,
    completionRate: 1,
    maxDepth: 0,
    activeWorkers: 0,
    stalledWorkers: 0,
    leafTasks: 1,
    completedOutputs: [
      {
        id: "task-1",
        title: "Task 1",
        status: "completed",
        depth: 0,
        executionMode: "local",
        orchestrationMode: "sequential",
        attempts: 1,
        maxAttempts: 3,
      },
    ],
    blockers: [],
  },
];

describe("createAgentOrchestratorPlugin", () => {
  it("exposes orchestration summary metadata from the native service", async () => {
    const plugin = createAgentOrchestratorPlugin({
      delegation: {
        create: () => ({
          id: "task-1",
          title: "Task 1",
          objective: "Do task 1",
          status: "pending",
          executionMode: "local",
          notes: [],
          createdAt: "2026-03-24T00:00:00.000Z",
          updatedAt: "2026-03-24T00:00:00.000Z",
        }),
        list: () => [
          {
            id: "task-1",
            title: "Task 1",
            objective: "Do task 1",
            status: "pending",
            executionMode: "local",
            notes: [],
            createdAt: "2026-03-24T00:00:00.000Z",
            updatedAt: "2026-03-24T00:00:00.000Z",
          },
          {
            id: "task-2",
            title: "Task 2",
            objective: "Do task 2",
            status: "running",
            executionMode: "delegated",
            notes: [],
            createdAt: "2026-03-24T00:00:00.000Z",
            updatedAt: "2026-03-24T00:00:00.000Z",
          },
        ],
        get: (id) => ({
          id,
          title: `Task ${id}`,
          objective: `Do ${id}`,
          status: "pending",
          executionMode: "local",
          notes: [],
          createdAt: "2026-03-24T00:00:00.000Z",
          updatedAt: "2026-03-24T00:00:00.000Z",
        }),
        queueSummary: () => ({
          total: 2,
          pending: 1,
          running: 1,
          completed: 0,
          failed: 0,
          cancelled: 0,
          retryable: 0,
          delegated: 1,
          local: 1,
          inlineWorkers: 0,
          processWorkers: 1,
          activeWorkers: 2,
          aliveWorkers: 1,
          stalledWorkers: 0,
          concurrency: 1,
          byProfile: [],
          byPriority: [],
          byGroup: [],
          byLabel: [],
          byOrchestration: [...orchestrationBreakdown],
        }),
        overview: () => ({
          total: 2,
          pending: 1,
          running: 1,
          completed: 0,
          failed: 0,
          cancelled: 0,
          retryable: 0,
          delegated: 1,
          local: 1,
          inlineWorkers: 0,
          processWorkers: 1,
          activeWorkers: 2,
          aliveWorkers: 1,
          stalledWorkers: 0,
          concurrency: 1,
          byProfile: [],
          byPriority: [],
          byGroup: [],
          byLabel: [],
          byOrchestration: [...orchestrationBreakdown],
        }),
        getChildren: () => [
          {
            id: "child-1",
            title: "Child 1",
            objective: "Do child 1",
            status: "pending",
            executionMode: "local",
            notes: [],
            createdAt: "2026-03-24T00:00:00.000Z",
            updatedAt: "2026-03-24T00:00:00.000Z",
          },
        ],
        tree: (id) => ({
          task: {
            id,
            title: `Task ${id}`,
            objective: `Do ${id}`,
            status: "pending",
            executionMode: "local",
            notes: [],
            createdAt: "2026-03-24T00:00:00.000Z",
            updatedAt: "2026-03-24T00:00:00.000Z",
          },
          children: [],
        }),
        spawnChild: () => ({
          id: "child-1",
          title: "Child 1",
          objective: "Do child 1",
          status: "pending",
          executionMode: "local",
          notes: [],
          createdAt: "2026-03-24T00:00:00.000Z",
          updatedAt: "2026-03-24T00:00:00.000Z",
        }),
        retryTask: () => ({
          id: "task-1",
          title: "Task 1",
          objective: "Do task 1",
          status: "pending",
          executionMode: "local",
          notes: [],
          createdAt: "2026-03-24T00:00:00.000Z",
          updatedAt: "2026-03-24T00:00:00.000Z",
        }),
        cancel: () => ({
          id: "task-1",
          title: "Task 1",
          objective: "Do task 1",
          status: "cancelled",
          executionMode: "local",
          notes: [],
          createdAt: "2026-03-24T00:00:00.000Z",
          updatedAt: "2026-03-24T00:00:00.000Z",
        }),
        supervise: async () => ({
          concurrency: 1,
          started: ["task-1"],
          completed: ["task-1"],
          failed: [],
          skipped: [],
          aggregations: completedAggregation,
          overview: {
            total: 2,
            pending: 1,
            running: 0,
            completed: 1,
            failed: 0,
            cancelled: 0,
            retryable: 0,
            delegated: 0,
            local: 2,
            inlineWorkers: 0,
            processWorkers: 0,
            activeWorkers: 2,
            aliveWorkers: 0,
            stalledWorkers: 0,
            concurrency: 1,
            byProfile: [],
            byPriority: [],
            byGroup: [],
            byLabel: [],
            byOrchestration: [...orchestrationBreakdown],
          },
        }),
        runQueued: async () => [
          {
            id: "task-1",
            title: "Task 1",
            objective: "Do task 1",
            status: "completed",
            executionMode: "local",
            notes: [],
            createdAt: "2026-03-24T00:00:00.000Z",
            updatedAt: "2026-03-24T00:00:00.000Z",
          },
        ],
      },
    });

    const ServiceCtor = plugin.services?.[0] as unknown as {
      start(runtime?: unknown): Promise<{
        summary(): unknown;
      }>;
    };
    const service = await ServiceCtor.start();
    expect(service.summary()).toEqual({
      tasks: 2,
      queuePending: 1,
      activeWorkers: 2,
      childTasksSupported: true,
      treeSupported: true,
      retrySupported: true,
    });
  });
});
