import type { loadGatewayConfig } from "@/config/gateway";
import type { NativeOwnershipCache } from "@/runtime/native/ownership-cache";
import type { AcpService } from "./acp";
import type { AgentSdkService } from "./agent-sdk-service";
import type { ApiTransportService } from "./api-transport-service";
import type { AutocoderPipelineService } from "./autocoder-pipeline/service";
import type { AwarenessService } from "./awareness-service";
import type { ContextCompressionService } from "./context-compression";
import type { ContextFilesService } from "./context-files-service";
import type { CronService } from "./cron/service";
import type { DelegationService } from "./delegation/service";
import type { DeliveryService } from "./delivery-service";
import type { DiagnosticsService } from "./diagnostics/service";
import type { DocumentsService } from "./documents-service";
import type { EcosystemService } from "./ecosystem-service";
import type { ExecutionApprovalService } from "./execution-approval/service";
import type { FuzzyPatchService } from "./fuzzy-patch";
import type { GatewaySessionService } from "./gateway-session-service";
import type { HooksService } from "./hooks-service";
import type { LoggerService } from "./logger-service";
import type { McpService } from "./mcp";
import type { MediaService } from "./media";
import type { MemoryService } from "./memory-service";
import type { NativeServiceRegistry } from "./native-service-registry";
import type { OperatorService } from "./operator/service";
import type { PairingService } from "./pairing-service";
import type { PersonalityService } from "./personality-service";
import type { RepositoryService } from "./repository-service";
import type { RunControllerService } from "./run-controller-service";
import type { SessionService } from "./session/service";
import type { SettingsService } from "./settings-service";
import type { SkillSynthesisService } from "./skill-synthesis/service";
import type { SkillsService } from "./skills/service";
import type { SkillsHubService } from "./skills-hub/service";
import type { StartupStateService } from "./startup-state-service";
import type { TerminalService } from "./terminal/service";
import type { ToolsService } from "./tools/service";
import type { TrajectoryService } from "./trajectory/service";
import type { UserProfileService } from "./user-profile/service";
import type { WebService } from "./web/service";
import type { WorkspaceService } from "./workspace-service/index";

export interface AppServices {
  apiTransport: ApiTransportService;
  agentSdk: AgentSdkService;
  nativeRegistry: NativeServiceRegistry;
  nativeOwnership: NativeOwnershipCache;
  memory: MemoryService;
  skills: SkillsService;
  skillsHub: SkillsHubService;
  sessions: SessionService;
  cron: CronService;
  pairing: PairingService;
  hooks: HooksService;
  logger: LoggerService;
  gatewaySessions: GatewaySessionService;
  executionApprovals: ExecutionApprovalService;
  delivery: DeliveryService;
  documents: DocumentsService;
  ecosystem: EcosystemService;
  gatewayConfig: ReturnType<typeof loadGatewayConfig>;
  personalities: PersonalityService;
  contextFiles: ContextFilesService;
  settings: SettingsService;
  workspace: WorkspaceService;
  terminal: TerminalService;
  repository: RepositoryService;
  diagnostics: DiagnosticsService;
  operator: OperatorService;
  tools: ToolsService;
  mcp: McpService;
  acp: AcpService;
  autocoderPipeline: AutocoderPipelineService;
  delegation: DelegationService;
  web: WebService;
  media: MediaService;
  trajectories: TrajectoryService;
  skillSynthesis: SkillSynthesisService;
  userProfiles: UserProfileService;
  contextCompression: ContextCompressionService;
  fuzzyPatch: FuzzyPatchService;
  runController: RunControllerService;
  awareness: AwarenessService;
  startupState: StartupStateService;
}
