import {
  getCliHelpExamples,
  getCliHotkeyBindings,
} from "@/cli/command-surface";
import { macAwareKeyLabel } from "@/cli/shell-chrome";

export function buildHelpText(agentName: string): string {
  const command = (value: string) => value.trim();
  const hotkeys = getCliHotkeyBindings();
  const examples = getCliHelpExamples();
  return [
    `${agentName} operator shell`,
    "",
    "Quick start:",
    "  Plain shell      Fast daily-driver loop for paired coding and shell work",
    "  Cockpit          Fullscreen observability for status, transports, and jobs",
    "  !cmd             Run a local shell command inline",
    "  /help            Show this guide",
    "",
    "One-shot views (from outside the shell):",
    "  doolittle status   Quick readiness and provider snapshot",
    "  doolittle progress Current run depth and tool activity",
    "  doolittle tools    Tool inventory and search surface",
    "  doolittle runtime  Native/runtime ownership details",
    "",
    "Daily loop:",
    "  Enter            Send message or command",
    `  ${macAwareKeyLabel("Ctrl-C")}           Cancel the active turn or leave when idle`,
    "  exit / quit      Leave the shell",
    "  /commands        Browse slash commands and bundled workflows",
    `  ${command("/status")}        Runtime, provider, and startup readiness`,
    `  ${command("/progress")}      Current run depth, tool activity, and turn state`,
    `  ${command("/accounts doctor")} Startup and linked-account diagnostics`,
    `  ${command("/gateway readiness")} Transport readiness and channel state`,
    `  ${command("/jobs")}          Background runs and detached work`,
    "",
    "Sessions:",
    `  ${command("/resume <title>")} Resume a named session`,
    `  ${command("/title <name>")}   Name the current session`,
    `  ${command("/sessions list")} Review recent sessions`,
    "",
    "Background jobs:",
    `  ${command("/jobs start <prompt>")} Start a detached background run`,
    `  ${command("/jobs show <id>")} Replay a job log`,
    `  ${command("/jobs attach <id>")} Follow a job live`,
    `  ${command("/jobs cancel <id>")} Cancel a background run`,
    "",
    "Cockpit hotkeys:",
    "  q                Quit",
    `  ${macAwareKeyLabel("Ctrl-C")}           Cancel the active turn or quit when idle`,
    "  Esc              Focus command input",
    `  ${macAwareKeyLabel("Ctrl-L")}           Clear transcript and activity`,
    `  ${macAwareKeyLabel("Ctrl-R")}           Refresh status panels`,
    `  ${macAwareKeyLabel("Ctrl-G")}           Switch to Gateway control deck`,
    `  ${macAwareKeyLabel("Ctrl-B")}           Switch to Background Jobs`,
    `  ${macAwareKeyLabel("Ctrl-P")}           Open command palette`,
    `  ${macAwareKeyLabel("Ctrl-E")}           Open multiline composer`,
    `  ${macAwareKeyLabel("Ctrl-S")}           Focus last response`,
    `  ${macAwareKeyLabel("Ctrl-X")}           Export transcript to clipboard/file`,
    `  ${macAwareKeyLabel("Alt-1..Alt-5")}     Show Assist/Ecosystem/Gateway/Responses/Jobs`,
    "  Tab              Complete the top suggested command",
    `  ${macAwareKeyLabel("PageUp/PageDown")}  Scroll the focused pane`,
    "  Up/Down          Command history in input",
    "  Ctrl-N/Ctrl-P    History + list navigation",
    "",
    "Hotkeys:",
    ...hotkeys.map(
      (entry) => `  ${entry.keys[0]?.toUpperCase()} ${command(entry.label)}`,
    ),
    `  ${macAwareKeyLabel("Ctrl-T")}           Next theme`,
    "",
    "Examples:",
    ...examples.map((entry) => `  ${command(entry)}`),
  ].join("\n");
}
