import { describe, expect, it } from "bun:test";
import { createBrowserPlugin } from "./index";

describe("createBrowserPlugin", () => {
  it("exposes browser-native operations and summary metadata", async () => {
    const plugin = createBrowserPlugin({
      browser: {
        status: async () => ({
          provider: "basic",
          ready: true,
          mode: "browser",
          detail: "ok",
          artifacts: {
            snapshot: true,
            screenshot: true,
            comparison: true,
          },
        }),
        fetchText: async (url) => ({
          url,
          text: "hello",
          provider: "basic",
          mode: "browser",
          renderedAt: "2026-03-24T00:00:00.000Z",
          contentType: "text/html",
          contentLength: 5,
          wordCount: 1,
          lineCount: 1,
          linkCount: 0,
          imageCount: 0,
          headingCount: 1,
          contentHash: "abc123",
        }),
        inspect: async (url) => ({
          page: {
            url,
            title: "Example",
            text: "hello",
            provider: "basic",
            mode: "browser",
            renderedAt: "2026-03-24T00:00:00.000Z",
            contentType: "text/html",
            contentLength: 5,
            wordCount: 1,
            lineCount: 1,
            linkCount: 0,
            imageCount: 0,
            headingCount: 1,
            contentHash: "abc123",
          },
          snapshotPath: `/tmp/${encodeURIComponent(url)}.md`,
          screenshotPath: `/tmp/${encodeURIComponent(url)}.png`,
          screenshotSvgPath: `/tmp/${encodeURIComponent(url)}.svg`,
          status: {
            provider: "basic",
            ready: true,
            mode: "browser",
            detail: "ok",
            artifacts: {
              snapshot: true,
              screenshot: true,
              comparison: true,
            },
          },
        }),
        snapshot: async (url) => `/tmp/${encodeURIComponent(url)}.md`,
        screenshot: async (url) => `/tmp/${encodeURIComponent(url)}.png`,
        capture: async (url) => ({
          page: {
            url,
            text: "hello",
            provider: "basic",
            mode: "browser",
            renderedAt: "2026-03-24T00:00:00.000Z",
            contentType: "text/html",
            contentLength: 5,
            wordCount: 1,
            lineCount: 1,
            linkCount: 0,
            imageCount: 0,
            headingCount: 1,
            contentHash: "abc123",
          },
          snapshotPath: `/tmp/${encodeURIComponent(url)}.md`,
          screenshotPath: `/tmp/${encodeURIComponent(url)}.png`,
          screenshotSvgPath: `/tmp/${encodeURIComponent(url)}.svg`,
          manifestPath: `/tmp/${encodeURIComponent(url)}.json`,
          reportPath: `/tmp/${encodeURIComponent(url)}.report.md`,
          status: {
            provider: "basic",
            ready: true,
            mode: "browser",
            detail: "ok",
            artifacts: {
              snapshot: true,
              screenshot: true,
              comparison: true,
            },
          },
        }),
        analyze: async (url) => ({
          focus: "browser",
          capture: {
            page: {
              url,
              text: "hello",
              provider: "basic",
              mode: "browser",
              renderedAt: "2026-03-24T00:00:00.000Z",
              contentType: "text/html",
              contentLength: 5,
              wordCount: 1,
              lineCount: 1,
              linkCount: 0,
              imageCount: 0,
              headingCount: 1,
              contentHash: "abc123",
            },
            snapshotPath: `/tmp/${encodeURIComponent(url)}.md`,
            screenshotPath: `/tmp/${encodeURIComponent(url)}.png`,
            screenshotSvgPath: `/tmp/${encodeURIComponent(url)}.svg`,
            manifestPath: `/tmp/${encodeURIComponent(url)}.json`,
            reportPath: `/tmp/${encodeURIComponent(url)}.report.md`,
            status: {
              provider: "basic",
              ready: true,
              mode: "browser",
              detail: "ok",
              artifacts: {
                snapshot: true,
                screenshot: true,
                comparison: true,
              },
            },
          },
          prompt: "analyze",
          highlights: [],
        }),
        compare: async (leftUrl, rightUrl) => ({
          left: {
            page: {
              url: leftUrl,
              text: "left",
              provider: "basic",
              mode: "browser",
              renderedAt: "2026-03-24T00:00:00.000Z",
              contentType: "text/html",
              contentLength: 4,
              wordCount: 1,
              lineCount: 1,
              linkCount: 0,
              imageCount: 0,
              headingCount: 1,
              contentHash: "left",
            },
            snapshotPath: "/tmp/left.md",
            screenshotPath: "/tmp/left.png",
            screenshotSvgPath: "/tmp/left.svg",
            manifestPath: "/tmp/left.json",
            reportPath: "/tmp/left.report.md",
            status: {
              provider: "basic",
              ready: true,
              mode: "browser",
              detail: "ok",
              artifacts: {
                snapshot: true,
                screenshot: true,
                comparison: true,
              },
            },
          },
          right: {
            page: {
              url: rightUrl,
              text: "right",
              provider: "basic",
              mode: "browser",
              renderedAt: "2026-03-24T00:00:00.000Z",
              contentType: "text/html",
              contentLength: 5,
              wordCount: 1,
              lineCount: 1,
              linkCount: 0,
              imageCount: 0,
              headingCount: 1,
              contentHash: "right",
            },
            snapshotPath: "/tmp/right.md",
            screenshotPath: "/tmp/right.png",
            screenshotSvgPath: "/tmp/right.svg",
            manifestPath: "/tmp/right.json",
            reportPath: "/tmp/right.report.md",
            status: {
              provider: "basic",
              ready: true,
              mode: "browser",
              detail: "ok",
              artifacts: {
                snapshot: true,
                screenshot: true,
                comparison: true,
              },
            },
          },
          manifestPath: "/tmp/compare.json",
          reportPath: "/tmp/compare.md",
          summary: {
            titleChanged: false,
            hashChanged: true,
            wordDelta: 1,
            linkDelta: 0,
            imageDelta: 0,
            headingDelta: 0,
          },
        }),
        analyzeComparison: async (leftUrl, rightUrl) => ({
          focus: "research",
          comparison: {
            left: {
              page: {
                url: leftUrl,
                text: "left",
                provider: "basic",
                mode: "browser",
                renderedAt: "2026-03-24T00:00:00.000Z",
                contentType: "text/html",
                contentLength: 4,
                wordCount: 1,
                lineCount: 1,
                linkCount: 0,
                imageCount: 0,
                headingCount: 1,
                contentHash: "left",
              },
              snapshotPath: "/tmp/left.md",
              screenshotPath: "/tmp/left.png",
              screenshotSvgPath: "/tmp/left.svg",
              manifestPath: "/tmp/left.json",
              reportPath: "/tmp/left.report.md",
              status: {
                provider: "basic",
                ready: true,
                mode: "browser",
                detail: "ok",
                artifacts: {
                  snapshot: true,
                  screenshot: true,
                  comparison: true,
                },
              },
            },
            right: {
              page: {
                url: rightUrl,
                text: "right",
                provider: "basic",
                mode: "browser",
                renderedAt: "2026-03-24T00:00:00.000Z",
                contentType: "text/html",
                contentLength: 5,
                wordCount: 1,
                lineCount: 1,
                linkCount: 0,
                imageCount: 0,
                headingCount: 1,
                contentHash: "right",
              },
              snapshotPath: "/tmp/right.md",
              screenshotPath: "/tmp/right.png",
              screenshotSvgPath: "/tmp/right.svg",
              manifestPath: "/tmp/right.json",
              reportPath: "/tmp/right.report.md",
              status: {
                provider: "basic",
                ready: true,
                mode: "browser",
                detail: "ok",
                artifacts: {
                  snapshot: true,
                  screenshot: true,
                  comparison: true,
                },
              },
            },
            manifestPath: "/tmp/compare.json",
            reportPath: "/tmp/compare.md",
            summary: {
              titleChanged: false,
              hashChanged: true,
              wordDelta: 1,
              linkDelta: 0,
              imageDelta: 0,
              headingDelta: 0,
            },
          },
          prompt: "compare",
          highlights: [],
        }),
      },
    });

    const ServiceCtor = plugin.services?.[0] as unknown as {
      start(runtime?: unknown): Promise<{
        summary(): unknown;
        fetch(url: string): Promise<unknown>;
      }>;
    };
    const service = await ServiceCtor.start();
    expect(service.summary()).toEqual({
      operations: [
        "status",
        "fetch",
        "inspect",
        "snapshot",
        "screenshot",
        "capture",
        "analyze",
        "compare",
        "analyzeComparison",
      ],
      multimodal: true,
      captureReady: true,
      analysisReady: true,
    });
    expect(await service.fetch("https://example.com")).toEqual({
      url: "https://example.com",
      text: "hello",
      provider: "basic",
      mode: "browser",
      renderedAt: "2026-03-24T00:00:00.000Z",
      contentType: "text/html",
      contentLength: 5,
      wordCount: 1,
      lineCount: 1,
      linkCount: 0,
      imageCount: 0,
      headingCount: 1,
      contentHash: "abc123",
    });
  });
});
