export const CHAT_WORKSPACE_CLASS = [
  "chat-workspace relative grid h-full max-h-full min-h-0 grid-cols-[minmax(0,1fr)] grid-rows-[minmax(0,1fr)] items-stretch overflow-hidden transition-[grid-template-columns] duration-200 ease-[var(--ease-out)]",
  "[&.inspector-open]:grid-cols-[minmax(0,1fr)_auto] max-[720px]:[&.inspector-open]:grid-cols-[minmax(0,1fr)]",
  "[&>.chat-conversation]:col-start-1 [&>.chat-conversation]:row-start-1",
  "[&>#thread-workbench]:col-start-2 [&>#thread-workbench]:row-start-1 [&>#thread-workbench]:grid [&>#thread-workbench]:h-full [&>#thread-workbench]:max-h-full [&>#thread-workbench]:min-h-0 [&>#thread-workbench]:min-w-0 [&>#thread-workbench]:self-stretch [&>#thread-workbench]:overflow-hidden max-[720px]:[&>#thread-workbench]:col-start-1",
  "[&_.chat-conversation]:grid [&_.chat-conversation]:h-full [&_.chat-conversation]:max-h-full [&_.chat-conversation]:min-h-0 [&_.chat-conversation]:min-w-0 [&_.chat-conversation]:w-full [&_.chat-conversation]:grid-rows-[minmax(0,1fr)_auto] [&_.chat-conversation]:overflow-hidden [&_.chat-conversation]:bg-[var(--bg)]",
  "[&_.chat-messages]:min-h-0 [&_.chat-messages]:min-w-0 [&_.chat-messages]:overflow-y-auto [&_.chat-messages]:overscroll-contain [&_.chat-messages]:px-[clamp(16px,4vw,56px)] [&_.chat-messages]:pt-5 [&_.chat-messages]:pb-3.5 [&_.chat-messages]:[scrollbar-gutter:stable] [&_.chat-messages]:[scroll-padding-bottom:150px] max-[720px]:[&_.chat-messages]:px-3 max-[720px]:[&_.chat-messages]:pt-3",
  "[&_.chat-loading]:flex [&_.chat-loading]:min-h-full [&_.chat-loading]:items-center [&_.chat-loading]:justify-center [&_.chat-loading]:gap-2 [&_.chat-loading]:text-[var(--muted)] [&_.chat-loading]:text-[length:var(--text-meta)]",
  "[&_.chat-progress]:mx-auto [&_.chat-progress]:mt-0 [&_.chat-progress]:mb-5 [&_.chat-progress]:flex [&_.chat-progress]:w-[min(100%,700px)] [&_.chat-progress]:items-center [&_.chat-progress]:gap-2 [&_.chat-progress]:text-[var(--muted)] [&_.chat-progress]:text-[length:var(--text-meta)]",
  "[&_.chat-loading_i]:size-2.75 [&_.chat-loading_i]:animate-spin [&_.chat-loading_i]:rounded-full [&_.chat-loading_i]:border [&_.chat-loading_i]:border-[var(--border-strong)] [&_.chat-loading_i]:border-t-[var(--accent)] [&_.chat-progress_i]:size-2.75 [&_.chat-progress_i]:animate-spin [&_.chat-progress_i]:rounded-full [&_.chat-progress_i]:border [&_.chat-progress_i]:border-[var(--border-strong)] [&_.chat-progress_i]:border-t-[var(--accent)]",
  "[&_.chat-welcome]:mx-auto [&_.chat-welcome]:flex [&_.chat-welcome]:min-h-full [&_.chat-welcome]:w-[min(100%,760px)] [&_.chat-welcome]:flex-col [&_.chat-welcome]:justify-center",
  "[&_.chat-welcome_h1]:mt-2 [&_.chat-welcome_h1]:mb-2.5 [&_.chat-welcome_h1]:max-w-170 [&_.chat-welcome_h1]:font-[var(--font-display)] [&_.chat-welcome_h1]:text-[length:var(--chat-welcome-title-size)] [&_.chat-welcome_h1]:leading-[1.05] [&_.chat-welcome_h1]:font-semibold [&_.chat-welcome_h1]:tracking-[-0.03em] [&_.chat-welcome_h1_em]:font-normal [&_.chat-welcome_h1_em]:text-[var(--accent)]",
  "[&_.chat-welcome>p]:m-0 [&_.chat-welcome>p]:max-w-140 [&_.chat-welcome>p]:text-xs [&_.chat-welcome>p]:leading-[1.65] [&_.chat-welcome>p]:text-[var(--muted)]",
  "[&_.starter-grid]:mt-5 [&_.starter-grid]:grid [&_.starter-grid]:w-[min(100%,660px)] [&_.starter-grid]:grid-cols-1 [&_.starter-grid]:gap-0 [&_.starter-grid]:border-t [&_.starter-grid]:border-[var(--border)]",
  "[&_.starter-grid_button]:grid [&_.starter-grid_button]:min-h-13 [&_.starter-grid_button]:grid-cols-[30px_minmax(0,1fr)_auto] [&_.starter-grid_button]:grid-rows-2 [&_.starter-grid_button]:items-center [&_.starter-grid_button]:gap-x-2.5 [&_.starter-grid_button]:gap-y-px [&_.starter-grid_button]:rounded-none [&_.starter-grid_button]:border-0 [&_.starter-grid_button]:border-b [&_.starter-grid_button]:border-[var(--border)] [&_.starter-grid_button]:bg-transparent [&_.starter-grid_button]:px-0.75 [&_.starter-grid_button]:py-2 [&_.starter-grid_button]:text-left [&_.starter-grid_button:hover]:bg-[color-mix(in_srgb,var(--accent)_5%,var(--surface))]",
  "[&_.starter-grid_button>span]:row-span-2 [&_.starter-grid_button>span]:font-[var(--font-mono)] [&_.starter-grid_button>span]:text-[var(--accent)] [&_.starter-grid_button>strong]:col-start-2 [&_.starter-grid_button>strong]:m-0 [&_.starter-grid_button>strong]:text-xs [&_.starter-grid_button>small]:col-start-2 [&_.starter-grid_button>small]:m-0 [&_.starter-grid_button>small]:text-[var(--muted)] [&_.starter-grid_button>small]:text-[length:var(--text-meta)] [&_.starter-grid_button>i]:col-start-3 [&_.starter-grid_button>i]:row-span-2 [&_.starter-grid_button>i]:not-italic [&_.starter-grid_button>i]:text-[var(--faint)]",
  "[&_.chat-message]:group [&_.chat-message]:mx-auto [&_.chat-message]:mb-1.25 [&_.chat-message]:w-[min(100%,880px)]",
  "[&_.chat-message-label]:mb-1.25 [&_.chat-message-label]:flex [&_.chat-message-label]:items-center [&_.chat-message-label]:justify-start [&_.chat-message-label]:gap-1.75",
  "[&_.chat-message-label_strong]:inline-flex [&_.chat-message-label_strong]:items-center [&_.chat-message-label_strong]:gap-2 [&_.chat-message-label_strong]:font-[var(--font-sans)] [&_.chat-message-label_strong]:text-[11px] [&_.chat-message-label_strong]:font-semibold [&_.chat-message-label_strong]:text-[var(--text-soft)] [&_.chat-message-label_time]:text-[9px] [&_.chat-message-label_time]:text-[var(--faint)]",
  "[&_.chat-message-avatar]:grid [&_.chat-message-avatar]:size-6.5 [&_.chat-message-avatar]:place-items-center [&_.chat-message-avatar]:rounded-[7px] [&_.chat-message-avatar]:border [&_.chat-message-avatar]:border-[color-mix(in_srgb,var(--accent)_22%,var(--border))] [&_.chat-message-avatar]:bg-[color-mix(in_srgb,var(--accent)_8%,var(--surface-soft))] [&_.chat-message-avatar]:font-[var(--font-mono)] [&_.chat-message-avatar]:text-[9px] [&_.chat-message-avatar]:font-bold [&_.chat-message-avatar]:text-[var(--accent)]",
  "[&_.chat-message-body]:ml-8.5 [&_.chat-message-body]:text-[length:var(--text-body)] [&_.chat-message-body]:leading-[1.68] [&_.chat-message-body]:text-[var(--text-soft)] max-[720px]:[&_.chat-message-body]:ml-0",
  "[&_.chat-message.error_.chat-message-body]:text-[var(--bad)]",
  "[&_.chat-message.user_.chat-message-label]:justify-end [&_.chat-message.user_.chat-message-label_strong]:order-2 [&_.chat-message.user_.chat-message-label_time]:order-1",
  "[&_.chat-message.user_.chat-message-avatar]:border-[var(--border)] [&_.chat-message.user_.chat-message-avatar]:bg-[var(--surface-soft)] [&_.chat-message.user_.chat-message-avatar]:text-[var(--text-soft)]",
  "[&_.chat-message.user_.chat-message-body]:ml-auto [&_.chat-message.user_.chat-message-body]:w-fit [&_.chat-message.user_.chat-message-body]:max-w-[min(76%,680px)] [&_.chat-message.user_.chat-message-body]:rounded-[12px_4px_12px_12px] [&_.chat-message.user_.chat-message-body]:border [&_.chat-message.user_.chat-message-body]:border-[color-mix(in_srgb,var(--border-strong)_72%,var(--border))] [&_.chat-message.user_.chat-message-body]:bg-[var(--surface-soft)] [&_.chat-message.user_.chat-message-body]:px-3.5 [&_.chat-message.user_.chat-message-body]:py-2.75 [&_.chat-message.user_.chat-message-body]:text-[var(--text)] max-[720px]:[&_.chat-message.user_.chat-message-body]:max-w-[90%]",
  "[&_.chat-message.user_.message-content__response_p]:whitespace-pre-wrap [&_.chat-message.user_.message-content__response_li]:whitespace-pre-wrap",
  "[&_.chat-message-footer]:mt-0.5 [&_.chat-message-footer]:ml-8.5 [&_.chat-message-footer]:flex [&_.chat-message-footer]:min-h-5 [&_.chat-message-footer]:min-w-0 [&_.chat-message-footer]:w-full [&_.chat-message-footer]:items-center [&_.chat-message-footer]:justify-start max-[720px]:[&_.chat-message-footer]:ml-0 [&_.chat-message.user_.chat-message-footer]:ml-0 [&_.chat-message.user_.chat-message-footer]:w-[min(100%,680px)] [&_.chat-message.user_.chat-message-footer]:justify-end",
  "[&_.chat-message-context-capsule]:mt-2 [&_.chat-message-context-capsule]:inline-flex [&_.chat-message-context-capsule]:max-w-[min(100%,36rem)] [&_.chat-message-context-capsule]:items-center [&_.chat-message-context-capsule]:gap-1.5 [&_.chat-message-context-capsule]:rounded-[7px] [&_.chat-message-context-capsule]:border [&_.chat-message-context-capsule]:border-[color-mix(in_srgb,var(--accent)_35%,transparent)] [&_.chat-message-context-capsule]:bg-[color-mix(in_srgb,var(--accent)_10%,var(--surface))] [&_.chat-message-context-capsule]:px-2 [&_.chat-message-context-capsule]:py-1 [&_.chat-message-context-capsule]:text-[0.78rem] [&_.chat-message-context-capsule]:text-[var(--muted)] [&_.chat-message-context-capsule>span:nth-child(2)]:truncate [&_.chat-message-context-capsule_small]:whitespace-nowrap [&_.chat-message-context-capsule_small]:text-[var(--faint)]",
  "[&_.chat-message-memory-source]:mt-2.5 [&_.chat-message-memory-source]:mb-0 [&_.chat-message-memory-source]:font-[var(--font-mono)] [&_.chat-message-memory-source]:text-[length:var(--text-meta)] [&_.chat-message-memory-source]:text-[var(--faint)]",
  "[&_.chat-message-attachments]:mt-3 [&_.chat-message-attachments]:mb-0.5 [&_.chat-message-attachments]:flex [&_.chat-message-attachments]:list-none [&_.chat-message-attachments]:flex-wrap [&_.chat-message-attachments]:gap-2 [&_.chat-message-attachments]:p-0",
  "[&_.chat-message-attachments_li]:flex [&_.chat-message-attachments_li]:min-w-42.5 [&_.chat-message-attachments_li]:items-center [&_.chat-message-attachments_li]:gap-2.5 [&_.chat-message-attachments_li]:rounded-[10px] [&_.chat-message-attachments_li]:border [&_.chat-message-attachments_li]:border-[color-mix(in_srgb,var(--accent)_24%,var(--border))] [&_.chat-message-attachments_li]:bg-[color-mix(in_srgb,var(--accent)_6%,var(--surface))] [&_.chat-message-attachments_li]:px-2.75 [&_.chat-message-attachments_li]:py-2.25",
  "[&_.chat-message-attachment-icon]:text-lg [&_.chat-message-attachment-icon]:text-[var(--accent)] [&_.chat-message-attachment-copy]:grid [&_.chat-message-attachment-copy]:min-w-0 [&_.chat-message-attachment-copy]:gap-0.5 [&_.chat-message-attachments_strong]:truncate [&_.chat-message-attachments_strong]:text-xs [&_.chat-message-attachments_strong]:font-semibold [&_.chat-message-attachments_strong]:text-[var(--text)] [&_.chat-message-attachments_small]:truncate [&_.chat-message-attachments_small]:text-[10px] [&_.chat-message-attachments_small]:text-[var(--muted)] [&_.chat-message-attachments_small]:capitalize",
  "[&_.chat-composer]:relative [&_.chat-composer]:mx-auto [&_.chat-composer]:mb-4 [&_.chat-composer]:grid [&_.chat-composer]:w-[min(calc(100%_-_36px),820px)] [&_.chat-composer]:min-w-0 [&_.chat-composer]:shrink-0 [&_.chat-composer]:grid-cols-[minmax(0,1fr)_auto] [&_.chat-composer]:items-end [&_.chat-composer]:gap-x-2.5 [&_.chat-composer]:gap-y-2 [&_.chat-composer]:rounded-[var(--radius-md)] [&_.chat-composer]:border [&_.chat-composer]:border-[var(--border-strong)] [&_.chat-composer]:bg-[var(--surface-raised)] [&_.chat-composer]:px-2.5 [&_.chat-composer]:pt-2.5 [&_.chat-composer]:pb-2 [&_.chat-composer]:shadow-[0_12px_32px_color-mix(in_srgb,var(--shadow)_34%,transparent)] max-[720px]:[&_.chat-composer]:mb-2 max-[720px]:[&_.chat-composer]:w-[calc(100%_-_16px)]",
  "[&_.chat-composer:has(textarea:focus-visible)]:border-[var(--accent)] [&_.chat-composer:has(textarea:focus-visible)]:shadow-[0_0_0_3px_color-mix(in_srgb,var(--accent)_38%,transparent),0_14px_42px_color-mix(in_srgb,var(--shadow)_24%,transparent)]",
  "[&_.chat-composer-input]:order-10 [&_.chat-composer-input]:col-span-full [&_.chat-composer-tools]:order-20 [&_.chat-composer-tools]:col-start-1 [&_.chat-composer-tools]:self-center [&_.chat-composer-submit]:order-21 [&_.chat-composer-submit]:col-start-2 [&_.chat-composer-submit]:self-center [&_.chat-composer-hint]:hidden",
  "[&_.chat-message-queue]:col-span-full [&_.chat-message-queue]:grid [&_.chat-message-queue]:gap-1.5 [&_.chat-message-queue]:border-b [&_.chat-message-queue]:border-[var(--border)] [&_.chat-message-queue]:px-0.5 [&_.chat-message-queue]:pt-0.5 [&_.chat-message-queue]:pb-1.5",
  "[&_.chat-message-queue-heading]:flex [&_.chat-message-queue-heading]:items-center [&_.chat-message-queue-heading]:justify-between [&_.chat-message-queue-heading]:gap-3 [&_.chat-message-queue-heading>span]:flex [&_.chat-message-queue-heading>span]:items-center [&_.chat-message-queue-heading>span]:gap-2.5",
  "[&_.chat-message-queue_strong]:font-[var(--font-mono)] [&_.chat-message-queue_strong]:text-[length:var(--text-meta)] [&_.chat-message-queue_strong]:tracking-[0.04em] [&_.chat-message-queue_strong]:text-[var(--accent)] [&_.chat-message-queue_strong]:uppercase [&_.chat-message-queue_button]:border-0 [&_.chat-message-queue_button]:bg-transparent [&_.chat-message-queue_button]:p-0 [&_.chat-message-queue_button]:text-[var(--muted)] [&_.chat-message-queue_button]:text-[length:var(--text-meta)] [&_.chat-message-queue_button:hover]:text-[var(--text)]",
  "[&_.chat-message-queue_ol]:grid [&_.chat-message-queue_ol]:max-h-28 [&_.chat-message-queue_ol]:gap-1 [&_.chat-message-queue_ol]:overflow-auto [&_.chat-message-queue_li]:grid [&_.chat-message-queue_li]:grid-cols-[18px_minmax(0,1fr)_auto_18px] [&_.chat-message-queue_li]:items-center [&_.chat-message-queue_li]:gap-1.75 [&_.chat-message-queue_li]:rounded-[var(--radius-xs)] [&_.chat-message-queue_li]:border [&_.chat-message-queue_li]:border-[var(--border)] [&_.chat-message-queue_li]:bg-[color-mix(in_srgb,var(--accent)_5%,var(--surface-soft))] [&_.chat-message-queue_li]:px-1.75 [&_.chat-message-queue_li]:py-1.25 [&_.chat-message-queue_li]:text-[var(--text-soft)]",
  "[&_.chat-message-queue_li>span]:grid [&_.chat-message-queue_li>span]:size-4.5 [&_.chat-message-queue_li>span]:place-items-center [&_.chat-message-queue_li>span]:rounded-[var(--radius-sm)] [&_.chat-message-queue_li>span]:bg-[var(--accent-soft)] [&_.chat-message-queue_li>span]:font-[var(--font-mono)] [&_.chat-message-queue_li>span]:text-[var(--accent)] [&_.chat-message-queue_li>span]:text-[length:var(--text-meta)] [&_.chat-message-queue_p]:truncate [&_.chat-message-queue_p]:text-[11px] [&_.chat-message-queue_small]:font-[var(--font-mono)] [&_.chat-message-queue_small]:text-[var(--muted)] [&_.chat-message-queue_small]:text-[length:var(--text-meta)]",
  "[&_.chat-file-context-list]:col-span-full [&_.chat-file-context-list]:flex [&_.chat-file-context-list]:list-none [&_.chat-file-context-list]:flex-wrap [&_.chat-file-context-list]:gap-1.5 [&_.chat-file-context-list]:px-0.5 [&_.chat-file-context-list]:pt-px [&_.chat-file-context-list]:pb-1",
  "[&_.chat-file-context-chip]:inline-flex [&_.chat-file-context-chip]:max-w-52.5 [&_.chat-file-context-chip]:items-center [&_.chat-file-context-chip]:gap-1.5 [&_.chat-file-context-chip]:rounded-full [&_.chat-file-context-chip]:border [&_.chat-file-context-chip]:border-[var(--accent-border)] [&_.chat-file-context-chip]:bg-[var(--accent-soft)] [&_.chat-file-context-chip]:py-1.25 [&_.chat-file-context-chip]:pr-1.25 [&_.chat-file-context-chip]:pl-2 [&_.chat-file-context-chip]:font-[var(--font-mono)] [&_.chat-file-context-chip]:text-[var(--text-soft)] [&_.chat-file-context-chip]:text-[length:var(--text-meta)] [&_.chat-file-context-chip__name]:truncate",
  "[&_.chat-file-context-chip__remove]:grid [&_.chat-file-context-chip__remove]:size-4 [&_.chat-file-context-chip__remove]:place-items-center [&_.chat-file-context-chip__remove]:rounded-full [&_.chat-file-context-chip__remove]:border-0 [&_.chat-file-context-chip__remove]:bg-transparent [&_.chat-file-context-chip__remove]:p-0 [&_.chat-file-context-chip__remove]:text-[var(--muted)] [&_.chat-file-context-chip__remove:hover]:bg-[color-mix(in_srgb,var(--accent)_12%,transparent)] [&_.chat-file-context-chip__remove:hover]:text-[var(--text)]",
  "[&_.chat-context-capsule]:col-span-full [&_.chat-context-capsule]:mx-3 [&_.chat-context-capsule]:mb-2 [&_.chat-context-capsule]:flex [&_.chat-context-capsule]:min-h-7.5 [&_.chat-context-capsule]:max-w-[calc(100%-24px)] [&_.chat-context-capsule]:items-center [&_.chat-context-capsule]:gap-1.75 [&_.chat-context-capsule]:rounded-lg [&_.chat-context-capsule]:border [&_.chat-context-capsule]:border-[color-mix(in_srgb,var(--accent)_45%,transparent)] [&_.chat-context-capsule]:bg-[color-mix(in_srgb,var(--accent)_12%,var(--surface-raised))] [&_.chat-context-capsule]:px-2 [&_.chat-context-capsule]:py-1 [&_.chat-context-capsule]:text-[var(--text-soft)] [&_.chat-context-capsule__label]:truncate [&_.chat-context-capsule_small]:whitespace-nowrap [&_.chat-context-capsule_small]:text-[var(--muted)] [&_.chat-context-capsule__remove]:ml-auto [&_.chat-context-capsule__remove]:border-0 [&_.chat-context-capsule__remove]:bg-transparent [&_.chat-context-capsule__remove]:px-1 [&_.chat-context-capsule__remove]:text-[var(--muted)]",
  "[&_.chat-attachment-summary]:col-span-full [&_.chat-attachment-summary]:px-0.75 [&_.chat-attachment-summary]:pt-px [&_.chat-attachment-summary]:pb-1.25 [&_.chat-attachment-summary]:font-[var(--font-mono)] [&_.chat-attachment-summary]:text-[length:var(--text-meta)] [&_.chat-attachment-summary]:text-[var(--faint)]",
  "[&_.chat-composer-validation]:col-span-full [&_.chat-composer-validation]:border-b [&_.chat-composer-validation]:border-[color-mix(in_srgb,var(--bad)_25%,var(--border))] [&_.chat-composer-validation]:px-0.75 [&_.chat-composer-validation]:pt-px [&_.chat-composer-validation]:pb-1.25 [&_.chat-composer-validation]:font-[var(--font-mono)] [&_.chat-composer-validation]:text-[var(--bad)] [&_.chat-composer-validation]:text-[length:var(--text-meta)]",
  "[&_.chat-memory-matches]:col-span-full [&_.chat-memory-matches]:grid [&_.chat-memory-matches]:min-w-0 [&_.chat-memory-matches]:gap-1.5 [&_.chat-memory-matches]:border-b [&_.chat-memory-matches]:border-[var(--border)] [&_.chat-memory-matches]:px-0.75 [&_.chat-memory-matches]:pt-1 [&_.chat-memory-matches]:pb-1.75 [&_.chat-memory-matches]:font-[var(--font-mono)] [&_.chat-memory-matches]:text-[var(--muted)] [&_.chat-memory-matches]:text-[length:var(--text-meta)]",
  "[&_.chat-memory-matches_strong]:font-semibold [&_.chat-memory-matches_strong]:tracking-[0.035em] [&_.chat-memory-matches_strong]:text-[var(--accent)] [&_.chat-memory-matches_strong]:uppercase [&_.chat-memory-matches_ul]:flex [&_.chat-memory-matches_ul]:min-w-0 [&_.chat-memory-matches_ul]:gap-1.5 [&_.chat-memory-matches_ul]:overflow-x-auto [&_.chat-memory-matches_li]:inline-flex [&_.chat-memory-matches_li]:max-w-60 [&_.chat-memory-matches_li]:min-w-0 [&_.chat-memory-matches_li]:items-center [&_.chat-memory-matches_li]:gap-1.25 [&_.chat-memory-matches_li]:whitespace-nowrap [&_.chat-memory-matches_li]:rounded-full [&_.chat-memory-matches_li]:border [&_.chat-memory-matches_li]:border-[color-mix(in_srgb,var(--accent)_18%,var(--border))] [&_.chat-memory-matches_li]:bg-[color-mix(in_srgb,var(--accent)_6%,var(--surface-soft))] [&_.chat-memory-matches_li]:px-1.75 [&_.chat-memory-matches_li]:py-1 [&_.chat-memory-matches_li]:text-[var(--text-soft)] [&_.chat-memory-matches_li_span]:truncate [&_.chat-memory-matches__kind]:text-[var(--accent)] [&_.chat-memory-matches__kind]:uppercase",
  "[&_.chat-storage-warning]:mx-auto [&_.chat-storage-warning]:mt-0 [&_.chat-storage-warning]:mb-3 [&_.chat-storage-warning]:w-[min(100%,760px)] [&_.chat-storage-warning]:rounded-[var(--radius-xs)] [&_.chat-storage-warning]:border [&_.chat-storage-warning]:border-[color-mix(in_srgb,var(--warn)_28%,var(--border))] [&_.chat-storage-warning]:bg-[color-mix(in_srgb,var(--warn)_8%,var(--surface))] [&_.chat-storage-warning]:px-2 [&_.chat-storage-warning]:py-1.25 [&_.chat-storage-warning]:font-[var(--font-mono)] [&_.chat-storage-warning]:text-[var(--warn)] [&_.chat-storage-warning]:text-[length:var(--text-meta)]",
  "[&_.chat-context-meter]:order-40 [&_.chat-context-meter]:col-span-full [&_.chat-context-meter]:grid [&_.chat-context-meter]:min-w-0 [&_.chat-context-meter]:grid-cols-[auto_minmax(72px,1fr)_auto] [&_.chat-context-meter]:items-center [&_.chat-context-meter]:gap-2.5 [&_.chat-context-meter]:border-t [&_.chat-context-meter]:border-[color-mix(in_srgb,var(--border)_72%,transparent)] [&_.chat-context-meter]:px-0.5 [&_.chat-context-meter]:pt-1.75 [&_.chat-context-meter]:text-[var(--muted)]",
  "[&_.chat-context-meter>span:last-child]:flex [&_.chat-context-meter>span:last-child]:items-baseline [&_.chat-context-meter>span:last-child]:gap-1.5 [&_.chat-context-meter>span:last-child]:whitespace-nowrap [&_.chat-context-meter>span:last-child]:font-[var(--font-mono)] [&_.chat-context-meter>span:last-child]:text-[length:var(--text-meta)] [&_.chat-context-meter_strong]:text-[var(--faint)] [&_.chat-context-meter_strong]:tracking-[0.06em] [&_.chat-context-meter_strong]:uppercase [&_.chat-context-meter_small]:text-[var(--muted)]",
  "[&_.chat-context-track]:h-0.75 [&_.chat-context-track]:overflow-hidden [&_.chat-context-track]:rounded-full [&_.chat-context-track]:bg-[color-mix(in_srgb,var(--text)_8%,transparent)] [&_.chat-context-fill]:block [&_.chat-context-fill]:h-full [&_.chat-context-fill]:min-w-0.5 [&_.chat-context-fill]:rounded-[inherit] [&_.chat-context-fill]:bg-[var(--accent)] [&_.chat-context-fill]:transition-[width] [&_.chat-context-fill]:duration-200 [&_.chat-context-meter.warn_.chat-context-fill]:bg-[var(--warn)] [&_.chat-context-meter.bad_.chat-context-fill]:bg-[var(--bad)]",
  "[&_.chat-prompt-library]:absolute [&_.chat-prompt-library]:bottom-[calc(100%+10px)] [&_.chat-prompt-library]:left-0 [&_.chat-prompt-library]:z-24 [&_.chat-prompt-library]:grid [&_.chat-prompt-library]:max-h-[min(440px,62vh)] [&_.chat-prompt-library]:w-[min(360px,calc(100vw-48px))] [&_.chat-prompt-library]:gap-2.5 [&_.chat-prompt-library]:overflow-auto [&_.chat-prompt-library]:rounded-[var(--radius-md)] [&_.chat-prompt-library]:border [&_.chat-prompt-library]:border-[var(--border-strong)] [&_.chat-prompt-library]:bg-[color-mix(in_srgb,var(--surface-raised)_98%,transparent)] [&_.chat-prompt-library]:p-3 [&_.chat-prompt-library]:text-[var(--text-soft)] [&_.chat-prompt-library]:shadow-[0_18px_48px_color-mix(in_srgb,var(--shadow)_78%,transparent)]",
  "[&_.chat-prompt-library>header]:flex [&_.chat-prompt-library>header]:items-start [&_.chat-prompt-library>header]:justify-between [&_.chat-prompt-library>header]:gap-3 [&_.chat-prompt-library__heading]:grid [&_.chat-prompt-library__heading]:gap-0.5 [&_.chat-prompt-library>header_strong]:text-xs [&_.chat-prompt-library>header_strong]:text-[var(--text)] [&_.chat-prompt-library>header_small]:text-[var(--faint)] [&_.chat-prompt-library>header_small]:text-[length:var(--text-meta)]",
  "[&_.chat-prompt-library__scope]:flex [&_.chat-prompt-library__scope]:gap-0.75 [&_.chat-prompt-library__scope]:rounded-[var(--radius-sm)] [&_.chat-prompt-library__scope]:border [&_.chat-prompt-library__scope]:border-[var(--border)] [&_.chat-prompt-library__scope]:bg-[var(--surface-soft)] [&_.chat-prompt-library__scope]:p-0.75 [&_.chat-prompt-library__scope_button]:min-w-0 [&_.chat-prompt-library__scope_button]:flex-1 [&_.chat-prompt-library__scope_button]:truncate [&_.chat-prompt-library__scope_button]:rounded-[var(--radius-xs)] [&_.chat-prompt-library__scope_button]:border-0 [&_.chat-prompt-library__scope_button]:bg-transparent [&_.chat-prompt-library__scope_button]:px-1.75 [&_.chat-prompt-library__scope_button]:py-1.25 [&_.chat-prompt-library__scope_button]:text-[var(--muted)] [&_.chat-prompt-library__scope_button]:text-[length:var(--text-meta)] [&_.chat-prompt-library__scope_button[aria-pressed=true]]:bg-[var(--surface-raised)] [&_.chat-prompt-library__scope_button[aria-pressed=true]]:text-[var(--text)]",
  "[&_.chat-prompt-library__save]:grid [&_.chat-prompt-library__save]:grid-cols-[minmax(0,1fr)_auto] [&_.chat-prompt-library__save]:gap-1.5 [&_.chat-prompt-library__save_input]:min-w-0 [&_.chat-prompt-library__save_input]:rounded-[var(--radius-sm)] [&_.chat-prompt-library__save_input]:border [&_.chat-prompt-library__save_input]:border-[var(--border)] [&_.chat-prompt-library__save_input]:bg-[var(--surface-soft)] [&_.chat-prompt-library__save_input]:px-2 [&_.chat-prompt-library__save_input]:py-1.75 [&_.chat-prompt-library__save_input]:text-[11px] [&_.chat-prompt-library__save_button]:rounded-[var(--radius-sm)] [&_.chat-prompt-library__save_button]:border-0 [&_.chat-prompt-library__save_button]:bg-[var(--accent)] [&_.chat-prompt-library__save_button]:px-2.25 [&_.chat-prompt-library__save_button]:py-1.75 [&_.chat-prompt-library__save_button]:text-[var(--accent-ink)] [&_.chat-prompt-library__save_button]:text-[length:var(--text-meta)] [&_.chat-prompt-library__save_button]:font-bold",
  "[&_.chat-prompt-library_ul]:grid [&_.chat-prompt-library_ul]:gap-0.75 [&_.chat-prompt-library_li]:grid [&_.chat-prompt-library_li]:grid-cols-[minmax(0,1fr)_auto] [&_.chat-prompt-library_li]:items-center [&_.chat-prompt-library_li]:gap-1.5 [&_.chat-prompt-library_li]:rounded-[var(--radius-sm)] [&_.chat-prompt-library_li]:border [&_.chat-prompt-library_li]:border-transparent [&_.chat-prompt-library_li]:px-1.5 [&_.chat-prompt-library_li]:py-1.25 [&_.chat-prompt-library_li:hover]:border-[var(--border)] [&_.chat-prompt-library_li:hover]:bg-[var(--surface-soft)] [&_.chat-prompt-library_li:focus-within]:border-[var(--border)] [&_.chat-prompt-library_li:focus-within]:bg-[var(--surface-soft)]",
  "[&_.chat-prompt-library__restore]:grid [&_.chat-prompt-library__restore]:min-w-0 [&_.chat-prompt-library__restore]:gap-0.5 [&_.chat-prompt-library__restore]:border-0 [&_.chat-prompt-library__restore]:bg-transparent [&_.chat-prompt-library__restore]:p-0 [&_.chat-prompt-library__restore]:text-left [&_.chat-prompt-library__restore_strong]:truncate [&_.chat-prompt-library__restore_strong]:text-[11px] [&_.chat-prompt-library__restore_strong]:text-[var(--text)] [&_.chat-prompt-library__restore_small]:truncate [&_.chat-prompt-library__restore_small]:text-[var(--faint)] [&_.chat-prompt-library__restore_small]:text-[length:var(--text-meta)]",
].join(" ");

export const CHAT_HEADER_CONTENT_CLASS = [
  "chat-header-content h-full min-w-0 w-full",
  "[&_.chat-header-mainline]:grid [&_.chat-header-mainline]:h-full [&_.chat-header-mainline]:min-w-0 [&_.chat-header-mainline]:grid-cols-[minmax(132px,0.7fr)_minmax(0,1fr)_auto] [&_.chat-header-mainline]:grid-rows-[44px] [&_.chat-header-mainline]:items-center [&_.chat-header-mainline]:gap-x-2.25 [&_.chat-header-mainline]:gap-y-1.5 max-[1440px]:[&_.chat-header-mainline]:grid-cols-[minmax(0,1fr)_auto] max-[980px]:[&_.chat-header-mainline]:grid-cols-1 max-[760px]:[&_.chat-header-mainline]:grid-rows-[34px]",
  "[&_.chat-header-title-wrap]:min-w-0 max-[980px]:[&_.chat-header-title-wrap]:hidden [&_h2]:truncate [&_h2]:m-0 [&_h2]:text-xs [&_h2]:leading-tight",
  "[&_.chat-session-meta-wrap]:min-w-0 [&_.chat-session-meta-wrap]:overflow-hidden max-[1440px]:[&_.chat-session-meta-wrap]:hidden",
  "[&_.chat-session-meta]:flex [&_.chat-session-meta]:min-w-0 [&_.chat-session-meta]:w-full [&_.chat-session-meta]:flex-nowrap [&_.chat-session-meta]:items-center [&_.chat-session-meta]:overflow-x-auto [&_.chat-session-meta]:[-webkit-app-region:no-drag]",
  "[&_.chat-session-meta-pill]:min-h-4 [&_.chat-session-meta-pill]:whitespace-nowrap [&_.chat-session-meta-pill]:border-0 [&_.chat-session-meta-pill]:border-r [&_.chat-session-meta-pill]:border-[var(--border)] [&_.chat-session-meta-pill]:bg-transparent [&_.chat-session-meta-pill]:px-1.25 [&_.chat-session-meta-pill]:text-[9px] [&_.chat-session-meta-pill]:text-[var(--faint)] [&_.chat-session-meta-pill:hover]:bg-[var(--surface-soft)] [&_.chat-session-meta-pill:hover]:text-[var(--text-soft)]",
  "[&_.chat-header-top-actions]:flex [&_.chat-header-top-actions]:min-w-0 [&_.chat-header-top-actions]:flex-nowrap [&_.chat-header-top-actions]:items-center [&_.chat-header-top-actions]:justify-end [&_.chat-header-top-actions]:gap-1 [&_.chat-header-top-actions]:[-webkit-app-region:no-drag] max-[980px]:[&_.chat-header-top-actions]:justify-between",
  "[&_.chat-context-compact]:inline-flex [&_.chat-context-compact]:min-h-4 [&_.chat-context-compact]:items-center [&_.chat-context-compact]:whitespace-nowrap [&_.chat-context-compact]:border-0 [&_.chat-context-compact]:bg-transparent [&_.chat-context-compact]:px-1.25 [&_.chat-context-compact]:font-[var(--font-mono)] [&_.chat-context-compact]:text-[9px] [&_.chat-context-compact]:text-[var(--muted)] [&_.chat-context-compact.context-warn]:text-[var(--warn)] [&_.chat-context-compact.context-bad]:text-[var(--bad)] max-[980px]:[&_.chat-context-compact]:hidden",
  "[&_.chat-model-route]:inline-flex [&_.chat-model-route]:min-h-4.5 [&_.chat-model-route]:items-center [&_.chat-model-route]:gap-1 [&_.chat-model-route]:whitespace-nowrap [&_.chat-model-route]:px-1.25 [&_.chat-model-route_strong]:text-[10px] [&_.chat-workbench-toggle]:inline-flex [&_.chat-workbench-toggle]:items-center [&_.chat-workbench-toggle]:gap-1.5 [&_.chat-workbench-toggle>span]:text-xs [&_.chat-workbench-toggle>span]:text-[var(--accent)]",
  "[&_.secondary-button]:inline-flex [&_.secondary-button]:min-h-8 [&_.secondary-button]:items-center [&_.secondary-button]:gap-1 [&_.secondary-button]:whitespace-nowrap [&_.secondary-button]:rounded-[var(--radius-xs)] [&_.secondary-button]:border [&_.secondary-button]:border-[var(--line-subtle)] [&_.secondary-button]:bg-[color-mix(in_srgb,var(--surface-soft)_82%,transparent)] [&_.secondary-button]:px-2 [&_.secondary-button]:py-0.5 [&_.secondary-button]:text-[11px] [&_.secondary-button]:font-semibold [&_.secondary-button]:text-[var(--text-soft)] [&_.secondary-button:hover]:border-[var(--border)] [&_.secondary-button:hover]:bg-[var(--surface-hover)] [&_.secondary-button:hover]:text-[var(--text)]",
  "[&_.chat-mobile-conversations-button]:hidden max-[980px]:[&_.chat-mobile-conversations-button]:inline-flex [&_.chat-mobile-conversations-button_small]:grid [&_.chat-mobile-conversations-button_small]:size-3.75 [&_.chat-mobile-conversations-button_small]:place-items-center [&_.chat-mobile-conversations-button_small]:rounded-full [&_.chat-mobile-conversations-button_small]:bg-[var(--accent-soft)] [&_.chat-mobile-conversations-button_small]:font-[var(--font-mono)] [&_.chat-mobile-conversations-button_small]:text-[8px] [&_.chat-mobile-conversations-button_small]:text-[var(--accent)]",
].join(" ");

export const MOBILE_CONVERSATIONS_BACKDROP_CLASS =
  "chat-mobile-conversations-backdrop fixed inset-0 z-100 block";
export const MOBILE_CONVERSATIONS_DISMISS_CLASS =
  "chat-mobile-conversations-dismiss absolute inset-0 border-0 bg-[color-mix(in_srgb,var(--shadow)_46%,transparent)]";
export const MOBILE_CONVERSATIONS_DIALOG_CLASS =
  "chat-mobile-conversations-dialog absolute inset-y-0 left-0 flex w-[min(390px,calc(100vw-56px))] flex-col gap-3 border-r border-[var(--border-strong)] bg-[var(--surface)] px-4.5 pt-6 pb-4.5 shadow-[18px_0_48px_color-mix(in_srgb,var(--shadow)_22%,transparent)] [&>header]:flex [&>header]:items-start [&>header]:justify-between [&>header_h2]:mt-1 [&>header_h2]:text-base [&>input]:h-9 [&>input]:w-full [&>input]:rounded-[var(--radius-sm)] [&>input]:border [&>input]:border-[var(--border)] [&>input]:bg-[var(--surface-soft)] [&>input]:px-2.5 [&>input]:py-1.75 max-[480px]:w-[calc(100vw-24px)]";
export const MOBILE_CONVERSATIONS_LIST_CLASS =
  "chat-mobile-conversations-list grid min-h-0 flex-1 content-start gap-0.5 overflow-y-auto [&>button]:flex [&>button]:min-w-0 [&>button]:flex-col [&>button]:gap-1 [&>button]:rounded-[var(--radius-sm)] [&>button]:border [&>button]:border-transparent [&>button]:bg-transparent [&>button]:p-2.25 [&>button]:text-left [&>button]:text-[var(--text-soft)] [&>button:hover]:border-[var(--border)] [&>button:hover]:bg-[var(--surface-hover)] [&>button:hover]:text-[var(--text)] [&>button[aria-current=page]]:border-[var(--border)] [&>button[aria-current=page]]:border-l-[var(--accent)] [&>button[aria-current=page]]:bg-[var(--surface-hover)] [&>button[aria-current=page]]:text-[var(--text)] [&_strong]:truncate [&_strong]:text-xs [&_span]:truncate [&_span]:font-[var(--font-mono)] [&_span]:text-[9px] [&_span]:text-[var(--muted)]";
export const MOBILE_CONVERSATIONS_NEW_CLASS =
  "new-chat-button w-full rounded-[var(--radius-xs)] border border-[var(--accent-border)] bg-[var(--accent-soft)] p-2.5 text-left text-[var(--text-soft)] text-[length:var(--text-meta)] font-semibold tracking-[0.04em] [&>span]:mr-1.5 [&>span]:text-[var(--accent)]";
