import type { NativePluginCatalogSeed } from "./types";

export const KNOWLEDGE_PLUGIN_CATALOG_SEEDS: NativePluginCatalogSeed[] = [
  {
    id: "knowledge.knowledge",
    packageName: "@elizaos/plugin-knowledge",
    category: "knowledge",
    source: "official",
    kind: "adapter",
    maturity: "alpha",
    enablement: "always",
    notes: "Official knowledge and ingestion service on the alpha line.",
  },
  {
    id: "knowledge.local-embedding",
    packageName: "@elizaos/plugin-local-embedding",
    category: "knowledge",
    source: "official",
    kind: "adapter",
    maturity: "alpha",
    enablement: "always",
    notes: "Official local embedding service on the alpha line.",
  },
  {
    id: "knowledge.personality",
    packageName: "@elizaos/plugin-personality",
    category: "knowledge",
    source: "official",
    kind: "adapter",
    maturity: "alpha",
    enablement: "always",
    notes: "Official personality service on the alpha line.",
  },
  {
    id: "knowledge.rolodex",
    packageName: "@elizaos/plugin-rolodex",
    category: "knowledge",
    source: "official",
    kind: "adapter",
    maturity: "alpha",
    enablement: "always",
    notes: "Official profile memory and rolodex service on the alpha line.",
  },
  {
    id: "knowledge.experience",
    packageName: "@elizaos/plugin-experience",
    category: "knowledge",
    source: "official",
    kind: "adapter",
    maturity: "alpha",
    enablement: "always",
    notes: "Official session and memory experience service on the alpha line.",
  },
];
