import type { NativePluginCatalogSeed } from "./types";

export const PROVIDER_PLUGIN_CATALOG_SEEDS: NativePluginCatalogSeed[] = [
  {
    id: "providers.sql",
    packageName: "@elizaos/plugin-sql",
    category: "providers",
    source: "official",
    kind: "provider",
    maturity: "production",
    enablement: "always",
    notes:
      "Official SQL persistence plugin; a private @doolittle/plugin-sql-relationships layer adds Doolittle's merge-on-write relationship semantics.",
  },
  {
    id: "providers.pdf",
    packageName: "@elizaos/plugin-pdf",
    category: "providers",
    source: "official",
    kind: "provider",
    maturity: "production",
    enablement: "always",
    notes: "Official PDF ingestion plugin.",
  },
  {
    id: "providers.elizacloud",
    packageName: "@elizaos/plugin-elizacloud",
    category: "providers",
    source: "official",
    kind: "provider",
    maturity: "production",
    enablement: "elizaCloud",
    notes:
      "Official ElizaOS Cloud plugin for managed inference, research, embeddings, media models, cloud status, and billing services.",
  },
  {
    id: "providers.ollama",
    packageName: "@elizaos/plugin-ollama",
    category: "providers",
    source: "official",
    kind: "provider",
    maturity: "alpha",
    enablement: "ollama",
    notes:
      "Official local/self-hosted Ollama provider for offline text, object, and embedding model routing.",
  },
  {
    id: "providers.codex",
    packageName: "@elizaos/plugin-codex-cli",
    category: "providers",
    source: "official",
    kind: "provider",
    maturity: "alpha",
    enablement: "codex",
    notes:
      "Official Eliza Codex model provider using the signed-in Codex CLI OAuth store, native tool calls, streaming, structured output, and atomic token refresh.",
  },
  {
    id: "providers.claude-code",
    packageName: "@elizaos/plugin-anthropic",
    category: "providers",
    source: "official",
    kind: "provider",
    maturity: "alpha",
    enablement: "claudeCode",
    notes:
      "Official Anthropic provider for linked Claude OAuth, account-pool rotation, native tools, structured output, streaming, and prompt caching; a narrow Doolittle bridge remains only for explicit structured CLI fallback.",
  },
  {
    id: "providers.devin",
    packageName: "@doolittle/plugin-devin",
    category: "providers",
    source: "custom",
    kind: "provider",
    maturity: "alpha",
    enablement: "devin",
    notes: "Doolittle-owned Devin CLI provider bridge for SWE model workflows.",
  },
  {
    id: "providers.openai",
    packageName: "@elizaos/plugin-openai",
    category: "providers",
    source: "official",
    kind: "provider",
    maturity: "production",
    enablement: "openai",
    notes: "Official OpenAI provider plugin.",
  },
  {
    id: "providers.anthropic",
    packageName: "@elizaos/plugin-anthropic",
    category: "providers",
    source: "official",
    kind: "provider",
    maturity: "production",
    enablement: "anthropic",
    notes: "Official Anthropic provider plugin.",
  },
];
