import type { NativePackageAuditRecord } from "../types";

export const NATIVE_EXECUTION_PACKAGE_AUDIT_RECORDS: NativePackageAuditRecord[] =
  [
    {
      packageName: "@elizaos/plugin-shell",
      role: "execution",
      currentStrategy: "official",
      currentTag: "alpha",
      latestTagVersion: "1.2.0",
      alphaTagVersion: "2.0.0-alpha.9",
      compatibility: "alpha-only",
      note: "Official shell plugin is now owned directly on the alpha line.",
    },
    {
      packageName: "@elizaos/plugin-e2b",
      role: "execution",
      currentStrategy: "official",
      currentTag: "workspace",
      latestTagVersion: "1.2.0",
      compatibility: "workspace-only",
      note: "Official E2B plugin is patched through the local workspace so its source can run cleanly on the alpha.85 stack.",
    },
    {
      packageName: "@elizaos/plugin-forms",
      role: "execution",
      currentStrategy: "vendored",
      currentTag: "workspace",
      latestTagVersion: "1.2.0",
      compatibility: "vendored-by-design",
      note: "Workspace-native forms plugin replaces the older published line so persistence and runtime lifecycle stay aligned with the alpha.85 stack.",
    },
    {
      packageName: "@elizaos/plugin-coding-agent",
      role: "execution",
      currentStrategy: "vendored",
      currentTag: "workspace",
      latestTagVersion: "0.1.0-next.0",
      alphaTagVersion: "0.1.0-alpha.1",
      compatibility: "vendored-by-design",
      note: "Still early-stage; kept vendored behind the stable app shell.",
    },
    {
      packageName: "@elizaos/plugin-agent-orchestrator",
      role: "execution",
      currentStrategy: "vendored",
      currentTag: "workspace",
      latestTagVersion: "0.3.9",
      alphaTagVersion: "0.3.16",
      compatibility: "vendored-by-design",
      note: "Modern enough for 2.x, but still best controlled through local vendoring.",
    },
    {
      packageName: "@elizaos/plugin-plugin-manager",
      role: "execution",
      currentStrategy: "official",
      currentTag: "alpha",
      latestTagVersion: "2.0.0-alpha.3",
      alphaTagVersion: "2.0.0-alpha.7",
      compatibility: "alpha-only",
      note: "Official plugin-manager package is now owned directly on the alpha line.",
    },
    {
      packageName: "@elizaos/plugin-planning",
      role: "execution",
      currentStrategy: "vendored",
      currentTag: "workspace",
      latestTagVersion: "1.2.0",
      alphaTagVersion: "2.0.0-alpha.3",
      compatibility: "vendored-by-design",
      note: "Workspace-native planning plugin links native delegation and workflow graphs on the alpha.85 stack.",
    },
  ];
