import type { NativePackageAuditRecord } from "../types";

export const NATIVE_FOUNDATION_PACKAGE_AUDIT_RECORDS: NativePackageAuditRecord[] =
  [
    {
      packageName: "elizaos",
      role: "runtime",
      currentStrategy: "official",
      currentTag: "beta",
      latestTagVersion: "1.7.2",
      betaTagVersion: "2.0.3-beta.7",
      compatibility: "beta-only",
      note: "Primary runtime package tracks the coherent beta line.",
    },
    {
      packageName: "@elizaos/core",
      role: "runtime-core",
      currentStrategy: "official",
      currentTag: "beta",
      latestTagVersion: "1.7.2",
      betaTagVersion: "2.0.3-beta.7",
      compatibility: "beta-only",
      note: "Core runtime tracks the coherent beta line.",
    },
    {
      packageName: "@elizaos/agent",
      role: "foundation",
      currentStrategy: "official",
      currentTag: "beta",
      latestTagVersion: "0.25.9",
      betaTagVersion: "2.0.3-beta.7",
      compatibility: "beta-only",
      note: "Standalone Eliza agent package provides registry and runtime-shape alignment on the beta line.",
    },
    {
      packageName: "@elizaos/shared",
      role: "foundation",
      currentStrategy: "official",
      currentTag: "beta",
      latestTagVersion: "2.0.0-alpha.144",
      betaTagVersion: "2.0.3-beta.7",
      compatibility: "beta-only",
      note: "Shared contracts and cloud helpers track the coherent beta line.",
    },
    {
      packageName: "@elizaos/skills",
      role: "foundation",
      currentStrategy: "official",
      currentTag: "beta",
      latestTagVersion: "2.0.0-alpha.77",
      betaTagVersion: "2.0.3-beta.7",
      compatibility: "beta-only",
      note: "Skills package tracks the coherent beta line through its published dist entrypoint.",
    },
  ];
