import type { NativePackageAuditRecord } from "../types";

export const NATIVE_INTERACTION_PACKAGE_AUDIT_RECORDS: NativePackageAuditRecord[] =
  [
    {
      packageName: "@elizaos/plugin-openai",
      role: "provider",
      currentStrategy: "official",
      currentTag: "alpha",
      latestTagVersion: "1.6.0",
      alphaTagVersion: "2.0.0-alpha.13",
      compatibility: "alpha-only",
      note: "Official provider is only practical on alpha for the 2.x runtime line.",
    },
    {
      packageName: "@elizaos/plugin-anthropic",
      role: "provider",
      currentStrategy: "official",
      currentTag: "alpha",
      latestTagVersion: "1.5.12",
      alphaTagVersion: "2.0.0-alpha.9",
      compatibility: "alpha-only",
      note: "Official provider is usable through alpha, not latest.",
    },
    {
      packageName: "@elizaos/plugin-pdf",
      role: "provider",
      currentStrategy: "official",
      currentTag: "alpha",
      latestTagVersion: "2.0.0-alpha.11",
      alphaTagVersion: "2.0.0-alpha.16",
      compatibility: "alpha-only",
      note: "Official PDF plugin tracks the 2.x line through alpha.",
    },
    {
      packageName: "@elizaos/plugin-sql",
      role: "provider",
      currentStrategy: "official",
      currentTag: "alpha",
      latestTagVersion: "2.0.0-alpha.11",
      alphaTagVersion: "2.0.0-alpha.17",
      compatibility: "alpha-only",
      note: "SQL stays on alpha to match the modern runtime path.",
    },
    {
      packageName: "@elizaos/plugin-telegram",
      role: "messaging",
      currentStrategy: "official",
      currentTag: "alpha",
      latestTagVersion: "1.6.4",
      alphaTagVersion: "2.0.0-alpha.11",
      compatibility: "alpha-only",
      note: "Official Telegram plugin is still 1.x on latest, so alpha is the usable modern line.",
    },
    {
      packageName: "@elizaos/plugin-discord",
      role: "messaging",
      currentStrategy: "official",
      currentTag: "alpha",
      latestTagVersion: "1.3.8",
      alphaTagVersion: "2.0.0-alpha.10",
      compatibility: "alpha-only",
      note: "Official Discord transport is now owned directly on the alpha line.",
    },
    {
      packageName: "@elizaos/plugin-browser",
      role: "browser",
      currentStrategy: "official",
      currentTag: "alpha",
      latestTagVersion: "1.0.3",
      alphaTagVersion: "2.0.0-alpha.9",
      compatibility: "alpha-only",
      note: "Official browser plugin is now owned directly on the alpha line.",
    },
    {
      packageName: "@elizaos/plugin-tts",
      role: "media",
      currentStrategy: "vendored",
      currentTag: "workspace",
      latestTagVersion: "0.25.6-alpha.1",
      alphaTagVersion: "2.0.0-alpha.7",
      compatibility: "vendored-by-design",
      note: "Workspace-native TTS plugin replaces the skewed published line so voice generation stays aligned with the alpha.85 runtime stack.",
    },
    {
      packageName: "@elizaos/plugin-mcp",
      role: "integration",
      currentStrategy: "official",
      currentTag: "alpha",
      latestTagVersion: "1.8.2",
      alphaTagVersion: "2.0.0-alpha.6",
      compatibility: "alpha-only",
      note: "Official MCP plugin is now owned directly on the alpha line.",
    },
    {
      packageName: "@elizaos/plugin-knowledge",
      role: "knowledge",
      currentStrategy: "official",
      currentTag: "alpha",
      latestTagVersion: "1.6.1",
      alphaTagVersion: "2.0.0-alpha.7",
      compatibility: "alpha-only",
      note: "Official knowledge plugin is now owned directly on the alpha line.",
    },
    {
      packageName: "@elizaos/plugin-local-embedding",
      role: "knowledge",
      currentStrategy: "official",
      currentTag: "alpha",
      latestTagVersion: "2.0.0-alpha.3",
      alphaTagVersion: "2.0.0-alpha.11",
      compatibility: "alpha-only",
      note: "Official local-embedding package is now owned directly on the alpha line.",
    },
    {
      packageName: "@elizaos/plugin-personality",
      role: "knowledge",
      currentStrategy: "official",
      currentTag: "alpha",
      latestTagVersion: "2.0.0-alpha.1",
      alphaTagVersion: "2.0.0-alpha.8",
      compatibility: "alpha-only",
      note: "Official personality package is now owned directly on the alpha line.",
    },
    {
      packageName: "@elizaos/plugin-rolodex",
      role: "knowledge",
      currentStrategy: "official",
      currentTag: "alpha",
      latestTagVersion: "2.0.0-alpha.3",
      alphaTagVersion: "2.0.0-alpha.9",
      compatibility: "alpha-only",
      note: "Official rolodex package is now owned directly on the alpha line.",
    },
    {
      packageName: "@elizaos/plugin-experience",
      role: "knowledge",
      currentStrategy: "official",
      currentTag: "alpha",
      latestTagVersion: "2.0.0-alpha.1",
      alphaTagVersion: "2.0.0-alpha.10",
      compatibility: "alpha-only",
      note: "Official experience package is now owned directly on the alpha line.",
    },
  ];
