import type { NativePackageAuditRecord } from "../types";

export const NATIVE_INTERACTION_PACKAGE_AUDIT_RECORDS: NativePackageAuditRecord[] =
  [
    {
      packageName: "@elizaos/plugin-openai",
      role: "provider",
      currentStrategy: "official",
      currentTag: "alpha",
      latestTagVersion: "1.6.0",
      alphaTagVersion: "2.0.0-alpha.537",
      compatibility: "alpha-only",
      note: "Official provider is only practical on alpha for the 2.x runtime line.",
    },
    {
      packageName: "@elizaos/plugin-anthropic",
      role: "provider",
      currentStrategy: "official",
      currentTag: "alpha",
      latestTagVersion: "1.5.12",
      alphaTagVersion: "2.0.0-alpha.537",
      compatibility: "alpha-only",
      note: "Official provider is usable through alpha, not latest.",
    },
    {
      packageName: "@elizaos/plugin-ollama",
      role: "provider",
      currentStrategy: "official",
      currentTag: "alpha",
      latestTagVersion: "2.0.0-alpha.537",
      alphaTagVersion: "2.0.0-alpha.537",
      compatibility: "alpha-only",
      note: "Installed alpha provider is the primary local Ollama implementation for text, object, and embedding models.",
    },
    {
      packageName: "@elizaos/plugin-pdf",
      role: "provider",
      currentStrategy: "official",
      currentTag: "alpha",
      latestTagVersion: "2.0.0-alpha.11",
      alphaTagVersion: "2.0.0-alpha.537",
      compatibility: "alpha-only",
      note: "Official PDF plugin tracks the 2.x line through alpha.",
    },
    {
      packageName: "@elizaos/plugin-sql",
      role: "provider",
      currentStrategy: "official",
      currentTag: "alpha",
      latestTagVersion: "1.7.2",
      alphaTagVersion: "2.0.0-alpha.20",
      compatibility: "alpha-only",
      note: "SQL stays on alpha to match the modern runtime path.",
    },
    {
      packageName: "@elizaos/plugin-telegram",
      role: "messaging",
      currentStrategy: "official",
      currentTag: "alpha",
      latestTagVersion: "1.6.4",
      alphaTagVersion: "2.0.0-alpha.537",
      compatibility: "alpha-only",
      note: "Official Telegram plugin is still 1.x on latest, so alpha is the usable modern line.",
    },
    {
      packageName: "@doolittle/plugin-personality",
      role: "knowledge",
      currentStrategy: "vendored",
      currentTag: "workspace",
      latestTagVersion: "consolidated",
      compatibility: "vendored-by-design",
      note: "Doolittle personality adapter is consolidated into doolittle-plugin while preserving local profile behavior.",
    },
    {
      packageName: "@doolittle/plugin-rolodex",
      role: "knowledge",
      currentStrategy: "vendored",
      currentTag: "workspace",
      latestTagVersion: "consolidated",
      compatibility: "vendored-by-design",
      note: "Doolittle rolodex adapter is consolidated into doolittle-plugin and backed by local user profiles.",
    },
    {
      packageName: "@doolittle/plugin-experience",
      role: "knowledge",
      currentStrategy: "vendored",
      currentTag: "workspace",
      latestTagVersion: "consolidated",
      compatibility: "vendored-by-design",
      note: "Doolittle experience adapter is consolidated into doolittle-plugin and backed by local sessions and memory.",
    },
  ];
