import type { NativePackageAuditRecord } from "../types";

export const NATIVE_INTERACTION_PACKAGE_AUDIT_RECORDS: NativePackageAuditRecord[] =
  [
    {
      packageName: "@elizaos/plugin-openai",
      role: "provider",
      currentStrategy: "official",
      currentTag: "beta",
      latestTagVersion: "1.6.0",
      betaTagVersion: "2.0.3-beta.7",
      compatibility: "beta-only",
      note: "Official provider tracks the coherent 2.x beta runtime line.",
    },
    {
      packageName: "@elizaos/plugin-anthropic",
      role: "provider",
      currentStrategy: "official",
      currentTag: "beta",
      latestTagVersion: "1.5.12",
      betaTagVersion: "2.0.3-beta.7",
      compatibility: "beta-only",
      note: "Official provider tracks the coherent 2.x beta runtime line.",
    },
    {
      packageName: "@elizaos/plugin-ollama",
      role: "provider",
      currentStrategy: "official",
      currentTag: "beta",
      latestTagVersion: "1.2.4",
      betaTagVersion: "2.0.3-beta.7",
      compatibility: "beta-only",
      note: "Installed beta provider is the primary local Ollama implementation for text, object, and embedding models.",
    },
    {
      packageName: "@elizaos/plugin-pdf",
      role: "provider",
      currentStrategy: "official",
      currentTag: "beta",
      latestTagVersion: "2.0.0-alpha.11",
      betaTagVersion: "2.0.3-beta.7",
      compatibility: "beta-only",
      note: "Official PDF plugin tracks the coherent 2.x beta line.",
    },
    {
      packageName: "@elizaos/plugin-sql",
      role: "provider",
      currentStrategy: "official",
      currentTag: "beta",
      latestTagVersion: "1.7.2",
      betaTagVersion: "2.0.3-beta.7",
      compatibility: "beta-only",
      note: "SQL stays on beta to match the modern runtime path.",
    },
    {
      packageName: "@elizaos/plugin-telegram",
      role: "messaging",
      currentStrategy: "official",
      currentTag: "beta",
      latestTagVersion: "1.6.4",
      betaTagVersion: "2.0.3-beta.7",
      compatibility: "beta-only",
      note: "Official Telegram plugin is still 1.x on latest, so beta is the usable modern line.",
    },
    {
      packageName: "@doolittle/plugin-personality",
      role: "knowledge",
      currentStrategy: "vendored",
      currentTag: "workspace",
      latestTagVersion: "consolidated",
      compatibility: "vendored-by-design",
      note: "Doolittle personality adapter is consolidated into doolittle-plugin while preserving local profile behavior.",
    },
    {
      packageName: "@doolittle/plugin-rolodex",
      role: "knowledge",
      currentStrategy: "vendored",
      currentTag: "workspace",
      latestTagVersion: "consolidated",
      compatibility: "vendored-by-design",
      note: "Doolittle rolodex adapter is consolidated into doolittle-plugin and backed by local user profiles.",
    },
    {
      packageName: "@doolittle/plugin-experience",
      role: "knowledge",
      currentStrategy: "vendored",
      currentTag: "workspace",
      latestTagVersion: "consolidated",
      compatibility: "vendored-by-design",
      note: "Doolittle experience adapter is consolidated into doolittle-plugin and backed by local sessions and memory.",
    },
  ];
