import type {
  ExecutionBackendName,
  RemoteArtifactPolicy,
  RemoteWorkspaceSyncMode,
} from "../execution";
import type { RunDepth, ToolProgressMode } from "./primitives";

export interface EnvConfig {
  agentName: string;
  mode: "api" | "cli" | "both";
  host: string;
  port: number;
  /** Bearer token required for non-loopback API binds (DOOLITTLE_API_TOKEN). */
  apiToken?: string;
  dataDir: string;
  skillsDir: string;
  timezone: string;
  elizaCloudApiKey?: string;
  elizaCloudEnabled: boolean;
  elizaCloudBaseUrl: string;
  elizaCloudSmallModel: string;
  elizaCloudLargeModel: string;
  elizaCloudEmbeddingModel: string;
  elizaCloudEmbeddingUrl?: string;
  elizaCloudEmbeddingApiKey?: string;
  elizaCloudEmbeddingDimensions?: number;
  ollamaApiEndpoint: string;
  ollamaSmallModel: string;
  ollamaLargeModel: string;
  ollamaEmbeddingModel: string;
  openAiApiKey?: string;
  offlineBootstrapMode: boolean;
  useLinkedCodexAuth: boolean;
  useLinkedDevinAuth: boolean;
  devinCliCommand: string;
  devinModel: string;
  devinTimeoutMs: number;
  openAiBaseUrl: string;
  openAiModel: string;
  openAiImageModel?: string;
  openAiTemperature: number;
  openAiMaxTokens: number;
  anthropicApiKey?: string;
  useLinkedClaudeCodeAuth: boolean;
  claudeCodeCliFallback: boolean;
  anthropicBaseUrl?: string;
  anthropicSmallModel: string;
  anthropicLargeModel: string;
  telegramBotToken?: string;
  telegramApiRoot?: string;
  telegramAllowedChats?: string;
  discordBotToken?: string;
  slackWebhookUrl?: string;
  slackSigningSecret?: string;
  whatsappAccessToken?: string;
  whatsappPhoneNumberId?: string;
  whatsappVerifyToken?: string;
  signalCliCommand?: string;
  matrixHomeserver?: string;
  matrixAccessToken?: string;
  emailSendCommand?: string;
  falApiKey?: string;
  smsSendCommand?: string;
  mattermostUrl?: string;
  mattermostToken?: string;
  homeAssistantUrl?: string;
  homeAssistantToken?: string;
  dingtalkWebhookUrl?: string;
  dingtalkAccessToken?: string;
  browserProvider: "lightpanda" | "basic";
  browserCommand: string;
  browserCdpUrl?: string;
  browserObeyRobots: boolean;
  remoteSyncMode: RemoteWorkspaceSyncMode;
  remoteSyncInclude: string[];
  remoteSyncExclude: string[];
  remoteArtifactPaths: string[];
  remoteArtifactPolicy: RemoteArtifactPolicy;
  remoteWorkspaceLabel: string;
  executionBackend: ExecutionBackendName;
  dockerImage: string;
  dockerNetwork: string;
  dockerWorkspacePath: string;
  dockerEnvPassthrough: string[];
  singularityImage: string;
  daytonaTarget?: string;
  daytonaCommand?: string;
  daytonaShell?: string;
  daytonaWorkspacePath?: string;
  daytonaSnapshot?: string;
  daytonaBootstrapCommand?: string;
  daytonaStatusCommand?: string;
  daytonaInspectCommand?: string;
  modalTarget?: string;
  modalCommand?: string;
  modalShell?: string;
  modalWorkspacePath?: string;
  modalEnvironment?: string;
  modalBootstrapCommand?: string;
  modalStatusCommand?: string;
  modalInspectCommand?: string;
  executionCommandTimeoutMs: number;
  executionHealthTimeoutMs: number;
  containerCpuLimit: string;
  containerMemoryLimit: string;
  containerPidsLimit: number;
  containerReadOnlyRoot: boolean;
  sshHost?: string;
  sshUser?: string;
  sshPath?: string;
  sshPort: number;
  sshKeyPath?: string;
  sshStrictHostKeyChecking: boolean;
  mcpServerCommand?: string;
  mcpTimeoutMs: number;
  acpServerCommand?: string;
  acpTimeoutMs: number;
  memoryCharLimit: number;
  userCharLimit: number;
  sessionSearchLimit: number;
  cronTickSeconds: number;
  cronOutputDir: string;
  gatewayDataDir: string;
  hooksDir: string;
  workspaceDir: string;
  allowAllUsers: boolean;
  pairingDefaultMode: "pair" | "deny" | "allow";
  runDepth: RunDepth;
  toolProgressMode: ToolProgressMode;
  maxIterations: number;
}
