/** Product design criteria, not a separate model call or a fixed visual theme. */
export const FRONTEND_DESIGN_CONTRACT = [
  "FRONTEND DESIGN WORKFLOW — applies when the assigned task creates or substantially redesigns a user-facing interface, not to backend-only work or narrow fixes:",
  "Read the project's existing brand brief, design tokens and components first. Preserve established identity and explicit user directions; do not rebrand a small fix. For a new interface with open design direction, choose a specific concept grounded in its audience and content rather than defaulting to a generic template. Resolve incidental choices yourself; ask only for missing decisions that materially change the requested outcome.",
  "Before implementing, form a compact brand/design brief: creative premise, composition and signature motif, semantic palette roles, deliberate typography hierarchy, imagery/art direction, density, and motion language. Carry that one coherent direction through the whole page. Use existing design documentation or your task report; do not create extra files outside the requested scope or overwrite an approved brand brief.",
  "Make the identity visible in the work: purposeful hierarchy and section rhythm, content-specific copy and imagery, considered color relationships, and component detail. A working page, default component library, stock hero plus repeated cards, or fashionable palette alone is not visual polish. Restraint and expressive design are both valid when intentional; do not impose a universal color, font, layout or aesthetic ban.",
  "For new interfaces, implement purposeful motion where it helps hierarchy or interaction, with a reduced-motion alternative and content visible without animation. Respect explicit no-animation requests. Use scoped transform/opacity/color transitions, useful hover/focus/active states, and working primary interactions; avoid decorative perpetual motion or transition-all.",
  "Verify desktop and narrow-screen composition, primary keyboard flows, focus visibility, and actual foreground/background text contrast including button labels. Inspect rendered-page pixels with an available real browser, not a fetched-text capture card. Do not claim visual inspection from DOM text, a PNG extension, or build success. If rendering is unavailable, report that limitation and distinguish source checks from rendered checks. In your final task report, name the chosen design direction and the specific checks run; never claim polish or complete visual verification without evidence.",
].join("\n");
